spring:
  data:
    mongodb:
      host: 172.31.5.105 # private subnet ip for mongoDB
      port: 27017
      database: Chatting

  redis:
    host: # private subnet ip for redis
    port: 6379
    database: 0