spring:
  data:
    mongodb:
      host: localhost # private subnet ip for mongoDB
      port: 27017
      database: Chatting

  redis:
    host: localhost
    port: 6379
    database: 0

management:
  endpoints:
    web:
      exposure:
        include: "*"